version: "3.9"

services:
  arch:
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - LOCALE=${LOCALE}
        - TIMEZONE=${TIMEZONE}
    container_name: "arch"
    ports:
      - 8022:22